### PR TITLE
Fix perfomance issue caused by Dictionary's swift_dynamicCast

### PR DESCRIPTION
**Pull request by yudoufu**
When I checked Himotoki's perfomance by [JSONShootout with Himotoki](https://github.com/yudoufu/JSONShootout/tree/add-himotoki-with-carthage-update), the result was very slow.
It was very sad... 😢  so I inspect the issue and I found reason.

It was caused by occured `swift_dynamicCast` by cast to `[String: Any]`  in `valueFor`.
So I fixed it to use NSDictionary for this cast, and the benchmark result changed very fast. 😄 

I want to review and merge this fix.

### CODE REVIEW

**Comment by ikesyo** [comment]
I'm sorry for the late response and really appreciate your contribution @yudoufu! ✨ 

I've slightly modified the pull request to cleanly introduce your proposed changes. Please let me know if you have further opinion against this. If you are okay I'll merge this and cut a new release.

**Comment by yudoufu** [comment]
@ikesyo Thank you for review and fix to my opinion.
I'm agree for your fix. It's make the most sense. 👍

**Comment by ikesyo** [comment]
:shipit:

**Comment by dcaunt** [comment]
Awesome!

@yudoufu do you intend to submit a PR to JSONShootout?

**Comment by yudoufu** [comment]
Yes, I will do it!
Thank you for comment @dcaunt :)

**Pull request merged**
