### PR TITLE
[CI][Travis] `-destination` should not be needed for Xcode 7.3

### PR DESCRIPTION
**Pull request by ikesyo**

### CODE REVIEW

**Comment by ikesyo** [comment]
:ship:

**Comment by toshi0383** [comment]
Just curious. Why do you not need -destination anymore ?

**Comment by ikesyo** [comment]
@toshi0383 In Xcode 7.2, we need to specify `-destination` for successful simulator builds as noted in https://github.com/Carthage/Carthage/pull/941. But in Xcode 7.3, it seems that the workaround is not needed anymore.

**Comment by toshi0383** [comment]
ic. thx!

**Pull request merged**
