### PR TITLE
Increase the number that can be handled

### PR DESCRIPTION
**Pull request by 335g**
I don't know what I should do how much larger. :sweat_smile:

### CODE REVIEW

**Comment by ikesyo** [comment]
@335g Thank you for the pull request! :sparkles: 

However, I'm hesitating about adding too many parameters support. IMHO, data types that have around 40 properties are something like a nightmare... :sweat: That would be a bad design and those types should be split into some subtypes, I think.

And do you need over 22 parameters support practically at now? If not, we should keep the functions as is, or it seems reasonable to support up to 26 parameters (yes, A to Z) at most. Do you have a specific, strong opinion about it?

Thanks anyway! :smiley:

**Comment by 335g** [comment]
Thank you for polite answer :bow: 

>  IMHO, data types that have around 40 properties are something like a nightmare... :sweat: That would be a bad design and those types should be split into some subtypes, I think.  

I also think so. I pull request because I didn't hit on a good idea. :sweat: 

> And do you need over 22 parameters support practically at now?  

Yes. I need to parse Twitter API. There is an endpoint that handle over 22 parameters (ex. 38 parameters in `user` of [statuses/home_timeline](https://dev.twitter.com/rest/reference/get/statuses/home_timeline))   

I close this PR. I use this branch for the time being. I hope to resolve in the near feature. I will PR if I will hit on a good idea :hand:

**Comment by ikesyo** [comment]
> Yes. I need to parse Twitter API. There is an endpoint that handle over 22 parameters (ex. 38 parameters in `user` of [statuses/home_timeline](https://dev.twitter.com/rest/reference/get/statuses/home_timeline))   

Oh, That's amazing... :astonished:

You might be able to omit some useless properties (e.g. "profile_...") or split them into a subtype like:

``` swift
struct User: Decodable {
    let name: String
    let id: String
    let location: String
    ...
    let profile: Profile

    struct Profile: Decodable {
        let sidebarFillColor: String
        let backgroundTitle: Bool
        let sidebarBorderColor: String
        ...

        static func decode(e: Extractor) -> Profile? { ... }
    }

    static func decode(e: Extractor) -> User? {
        let create = { User($0) }
        return build(
            e <| "name",
            e <| "id_str",
            e <| "location",
            ...,
            Profile.decode(e)
        ).map(create)
    }
}
```

**Comment by 335g** [comment]
Thanks for showing detail :sparkles:  
I didn't know how to split them into a subtype. I will fix in this way. :+1:

**Pull request closed without merging**
